chain_service:
  provider: quicknode
  endpoint: https://docs-demo.quiknode.pro/
  maxcredit: 350
rpc:
  address: 127.0.0.1:50051
db:
  host: localhost
  port: 5432
  user: postgres
  password: 123
  dbname: mydb