[package]
name = "rpc"
version = "0.1.0"
edition = "2021"

[dependencies]
tonic = "0.11.0"
tonic-build = "0.11.0"
prost = "0.12.6"
tokio = { version = "1", features = ["full", "test-util"] }
workflow ={version = "0.1.0", path = "../workflow"}
log = "0.4.22"
futures = "0.3.30"
